name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |
          cd ~/devops_project

          git pull origin main

          sudo docker stop ml-app || true
          sudo docker rm ml-app || true

          sudo docker build -t ml-app .

          sudo docker run -d \
          --name ml-app \
          -p 8501:8501 \
          --restart unless-stopped \
          ml-app